<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <RootNamespace>GlassSuite</RootNamespace>
    <AssemblyName>GlassSuite</AssemblyName>
    <ApplicationIcon />
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.2.2" />
    <PackageReference Include="LibVLCSharp.WPF" Version="3.8.2" />
    <PackageReference Include="VideoLAN.LibVLC.Windows" Version="3.0.20" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Assets\legal\*.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
